{
 "title": "gitea",
 "description": "gitea dashboard for prometheus exporter",
 "tags": [
  "gitea",
  "git"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Achievements",
   "type": "graph",
   "description": "Milestones, Follows, Stars, Releases",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitea_milestones", "legendFormat": "Milestones" },
    { "expr": "gitea_follows", "legendFormat": "Follows" },
    { "expr": "gitea_stars", "legendFormat": "Stars" },
    { "expr": "gitea_releases", "legendFormat": "Releases" }
   ]
  },
  {
   "title": "Contributions",
   "type": "graph",
   "description": "Comments, Issues, Stars, Mirrors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitea_repositories", "legendFormat": "Repositories" },
    { "expr": "gitea_comments", "legendFormat": "Comments" },
    { "expr": "gitea_issues", "legendFormat": "Issues" },
    { "expr": "gitea_mirrors", "legendFormat": "Mirrors" }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "description": "Users, Organisations, Teams",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitea_users", "legendFormat": "Users" },
    { "expr": "gitea_organizations", "legendFormat": "Organisations" },
    { "expr": "gitea_teams", "legendFormat": "Teams" }
   ]
  }
 ]
}